# OAK_CARGO_DEPRECATED
# Please use Oak via Bazel. Cargo support is deprecated.

[package]
name = "oak_proto_rust"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"

[features]
default = []
std = []

[dependencies]
prost = { workspace = true, default-features = false, features = [
  "prost-derive",
] }
prost-types = { version = "*", default-features = false }
serde = "*"
base64 = ">= 0.21"

[build-dependencies]
prost-build = { workspace = true }
pbjson-build = { version = "*", optional = true }
