[package]
name = "oak_session"
version = "0.1.0"
authors = ["Ivan Petrov <ivanpetrov@google.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
aead = { version = "*", default-features = false }
anyhow = { version = "*", default-features = false }
derive_builder = { version = "0.20.0", default-features = false, features = [
  "alloc",
] }
itertools = { version = "*", default-features = false }
oak_attestation_types = { workspace = true }
oak_attestation_verification = { workspace = true }
oak_attestation_verification_types = { workspace = true }
oak_crypto = { workspace = true }
oak_proto_rust = { workspace = true }
p256 = { version = "*", default-features = false }
prost = { version = "*", default-features = false }

[dev-dependencies]
mockall = { version = "*", default-features = false }
rand_core = { version = "*", default-features = false }
