[package]
name = "oak_containers_stage1"
version = "0.1.0"
edition = "2021"
authors = ["Andri Saar <andrisaar@google.com>"]
license = "Apache-2.0"

[build-dependencies]
oak_grpc_utils = { workspace = true }

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
futures-util = "*"
oak_attestation = { workspace = true }
oak_attestation_types = { workspace = true }
oak_crypto = { workspace = true }
oak_dice = { workspace = true }
oak_proto_rust = { workspace = true }
oak_grpc = { workspace = true }
oak_containers_stage1_dice = { workspace = true }
oak_containers_channel = { workspace = true }
nix = { version = "0.27.1", features = ["mman"] }
p256 = { version = "*" }
prost = { workspace = true }
rand_core = { version = "*", default-features = false, features = [
  "getrandom",
] }
rtnetlink = "*"
tar = "*"
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "process",
  "sync",
] }
tonic = { workspace = true }
x86_64 = "*"
xz2 = "*"
zerocopy = "*"
zeroize = "*"
