[package]
name = "oak_containers_hello_world_untrusted_app"
version = "0.1.0"
authors = ["Juliette Pretot <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"

[features]
bazel = []

[build-dependencies]
oak_grpc_utils = { workspace = true }

[dependencies]
anyhow = "*"
async-stream = "*"
async-trait = "*"
bytes = "*"
clap = { version = "*", features = ["derive"] }
env_logger = "*"
futures = "*"
http-body-util = "*"
hyper = { version = "1.4.1", features = ["full"] }
hyper-util = { version = "*", features = ["full"] }
log = "*"
oak_client = { workspace = true }
oak_client_tonic = { workspace = true }
oak_containers_launcher = { workspace = true }
oak_crypto = { workspace = true }
oak_hello_world_proto = { path = "../proto" }
oak_proto_rust = { workspace = true }
prost = "*"
tokio = { version = "*", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
tokio-stream = { version = "*" }
tonic = "*"
tower = "*"
which = "*"

[dev-dependencies]
once_cell = "*"
oak_functions_test_utils = { workspace = true }
