# OAK_CARGO_DEPRECATED
# Please use Oak via Bazel. Cargo support is deprecated.

[package]
name = "oak_containers_channel"
version = "0.1.0"
authors = ["Oak team"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
anyhow = "*"
tonic = { workspace = true }
tokio-vsock = { version = "*", features = ["tonic-conn"] }
tower = "*"
[dev-dependencies]
oak_proto_rust = { workspace = true }
oak_grpc = { workspace = true }
tokio = { version = "*", features = ["sync", "macros"] }
async-stream = "*"
tokio-stream = { version = "*", features = ["net"] }
futures = "*"
