[package]
name = "oak_file_utils"
version = "0.1.0"
authors = ["Juliette Pluto <julsh@google.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Shared utilities file access"

[features]
bazel = []
default = []
